---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  chart:
    spec:
      chart: cilium
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  upgrade:
    crds: CreateReplace
  install:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: base-cilium-helm-values
  - kind: ConfigMap
    name: cilium-helm-values
