---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
configMapGenerator:
  - name: cilium-helm-values
    files:
      - values.yaml=cilium-helm-values.yaml
resources:
  - ../../../base/cilium
  - cilium-helmRelease.yaml
configurations:
  - kustomize-nameReference.yaml
