---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-blackbox-exporter
  namespace: flux-system
spec:
  interval: 6h
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./flux/applications/dev-cliip/prometheus-blackbox-exporter
  prune: true
  timeout: 10m
  retryInterval: 2m
  wait: false
