---
apiVersion: v1
kind: Secret
metadata:
  name: clab-gitlab-runner-authentication-token
  namespace: clab-gitlab-runner
type: Opaque
data:
  runner-registration-token: IiI=
  runner-token: "RunnerToken"
