---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-blackbox-exporter
  namespace: prometheus-blackbox-exporter
spec:
  type: oci
  url: oci://ghcr.io/prometheus-community/charts
