---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 6h
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.7
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  upgrade:
    crds: CreateReplace
  install:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: base-ingress-nginx-helm-values
  - kind: ConfigMap
    name: ingress-nginx-helm-values
