---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-blackbox-exporter
  namespace: prometheus-blackbox-exporter
spec:
  interval: 12h
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 11.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-blackbox-exporter
        namespace: prometheus-blackbox-exporter
  upgrade:
    crds: CreateReplace
  install:
    crds: CreateReplace
  valuesFrom:
  - kind: ConfigMap
    name: base-prometheus-blackbox-exporter-helm-values
  - kind: ConfigMap
    name: prometheus-blackbox-exporter-helm-values
