---
apiVersion: v1
kind: Service
metadata:
  name: netbox-postgres
  namespace: netbox
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app.kubernetes.io/name: netbox-postgres
