---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gnmic-targets
  namespace: network-monitoring
data:
  targets.gnmic.yaml: |
    ---
    SW01:
      address: 172.16.103.10:6030
    SW02:
      address: 172.16.103.20:6030
