---
apiVersion: v1
kind: Secret
metadata:
  name: gnmic-config
  namespace: network-monitoring
type: Opaque
stringData:
  config.gnmic.yaml: |
    ---
    encoding: proto
    log: true
    insecure: true

    loader:
      type: file
      path: /app/targets.gnmic.yaml
      interval: 30s
      enable-metrics: false

    subscriptions:
      arista_stream_sample:
        paths:
          - /interfaces/interface
        mode: stream
        stream-mode: sample
        sample-interval: 5s

    outputs:
      prometheus:
        type: prometheus
        listen: ":9804"
        path: /metrics
        metric-prefix: gnmic
        debug: false
        expiration: -1s
