---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: netbox
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    app.kubernetes.io/name: redis
